package controller.modelos;
// Generated 25-03-2018 21:44:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,schema="solnatura"
)
public class Producto  implements java.io.Serializable {


     private int id;
     private String nombreProducto;
     private Integer codigoProducto;
     private Date creado;
     private Date actualizado;

    public Producto() {
    }

	
    public Producto(int id) {
        this.id = id;
    }
    public Producto(int id, String nombreProducto, Integer codigoProducto, Date creado, Date actualizado) {
       this.id = id;
       this.nombreProducto = nombreProducto;
       this.codigoProducto = codigoProducto;
       this.creado = creado;
       this.actualizado = actualizado;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre_producto", length=100)
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }

    
    @Column(name="codigo_producto")
    public Integer getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(Integer codigoProducto) {
        this.codigoProducto = codigoProducto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creado", length=29)
    public Date getCreado() {
        return this.creado;
    }
    
    public void setCreado(Date creado) {
        this.creado = creado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="actualizado", length=29)
    public Date getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(Date actualizado) {
        this.actualizado = actualizado;
    }

}


